# [--- Day 4: Giant Squid ---](https://adventofcode.com/2021/day/4)

You're already almost 1.5km (almost a mile) below the surface of the ocean, already so deep that you can't see any sunlight. What you can see, however, is a giant squid that has attached itself to the outside of your submarine.

Maybe it wants to play bingo?

Bingo is played on a set of boards each consisting of a 5x5 grid of numbers. Numbers are chosen at random, and the chosen number is marked on all boards on which it appears. (Numbers may not appear on all boards.) If all numbers in any row or any column of a board are marked, that board wins. (Diagonals don't count.)

The submarine has a bingo subsystem to help passengers (currently, you and the giant squid) pass the time. It automatically generates a random order in which to draw numbers and a random set of boards (your puzzle input).

Visit https://adventofcode.com/2021/day/4 for example

The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board; in this case, the sum is 188. Then, multiply that sum by the number that was just called when the board won, 24, to get the final score, 188 * 24 = 4512.

To guarantee victory against the giant squid, figure out which board will win first. 

What will your final score be if you choose that board?


In [1]:
# First Create a function to read the text input
def get_inputs(filepath):
    file = open(filepath)
    report = file.readlines()
    ## Removing \n from every line
    report = [rep[:-1] for rep in report]
    return report

In [2]:
input = get_inputs("puzzleinput.txt")
input[:13]

['42,44,71,26,70,92,77,45,6,18,79,54,31,34,64,32,16,55,81,11,90,10,21,87,0,84,8,23,1,12,60,20,57,68,61,82,49,59,22,2,63,33,50,39,28,30,88,41,69,72,98,73,7,65,53,35,96,67,36,4,51,75,24,86,97,85,66,29,74,40,93,58,9,62,95,91,80,99,14,19,43,37,27,56,94,25,83,48,17,38,78,15,52,76,5,13,46,89,47,3',
 '',
 '48 69 68 49 13',
 '25 14 30 74 89',
 '16 38 19 24 29',
 '56 97 50 65 79',
 '57 52  5 27 76',
 '',
 '65 69 73 60 66',
 '79 23 95 32 56',
 '36 51 26  1 28',
 '76  9  3 71 77',
 '41 15 61 68 14']

In [3]:
# Seperate random numbers from boards from board
rand_nums = input[0]
rand_nums

'42,44,71,26,70,92,77,45,6,18,79,54,31,34,64,32,16,55,81,11,90,10,21,87,0,84,8,23,1,12,60,20,57,68,61,82,49,59,22,2,63,33,50,39,28,30,88,41,69,72,98,73,7,65,53,35,96,67,36,4,51,75,24,86,97,85,66,29,74,40,93,58,9,62,95,91,80,99,14,19,43,37,27,56,94,25,83,48,17,38,78,15,52,76,5,13,46,89,47,3'

In [4]:
rand_nums = rand_nums.split(",")
rand_nums

['42',
 '44',
 '71',
 '26',
 '70',
 '92',
 '77',
 '45',
 '6',
 '18',
 '79',
 '54',
 '31',
 '34',
 '64',
 '32',
 '16',
 '55',
 '81',
 '11',
 '90',
 '10',
 '21',
 '87',
 '0',
 '84',
 '8',
 '23',
 '1',
 '12',
 '60',
 '20',
 '57',
 '68',
 '61',
 '82',
 '49',
 '59',
 '22',
 '2',
 '63',
 '33',
 '50',
 '39',
 '28',
 '30',
 '88',
 '41',
 '69',
 '72',
 '98',
 '73',
 '7',
 '65',
 '53',
 '35',
 '96',
 '67',
 '36',
 '4',
 '51',
 '75',
 '24',
 '86',
 '97',
 '85',
 '66',
 '29',
 '74',
 '40',
 '93',
 '58',
 '9',
 '62',
 '95',
 '91',
 '80',
 '99',
 '14',
 '19',
 '43',
 '37',
 '27',
 '56',
 '94',
 '25',
 '83',
 '48',
 '17',
 '38',
 '78',
 '15',
 '52',
 '76',
 '5',
 '13',
 '46',
 '89',
 '47',
 '3']

In [5]:
# Change strings to int
rand_nums = [int(ran) for ran in rand_nums]
rand_nums

[42,
 44,
 71,
 26,
 70,
 92,
 77,
 45,
 6,
 18,
 79,
 54,
 31,
 34,
 64,
 32,
 16,
 55,
 81,
 11,
 90,
 10,
 21,
 87,
 0,
 84,
 8,
 23,
 1,
 12,
 60,
 20,
 57,
 68,
 61,
 82,
 49,
 59,
 22,
 2,
 63,
 33,
 50,
 39,
 28,
 30,
 88,
 41,
 69,
 72,
 98,
 73,
 7,
 65,
 53,
 35,
 96,
 67,
 36,
 4,
 51,
 75,
 24,
 86,
 97,
 85,
 66,
 29,
 74,
 40,
 93,
 58,
 9,
 62,
 95,
 91,
 80,
 99,
 14,
 19,
 43,
 37,
 27,
 56,
 94,
 25,
 83,
 48,
 17,
 38,
 78,
 15,
 52,
 76,
 5,
 13,
 46,
 89,
 47,
 3]

Now that randon numbers are ready, get the boards ready

In [6]:
boards = input[2:]

In [7]:
# View boards
boards

['48 69 68 49 13',
 '25 14 30 74 89',
 '16 38 19 24 29',
 '56 97 50 65 79',
 '57 52  5 27 76',
 '',
 '65 69 73 60 66',
 '79 23 95 32 56',
 '36 51 26  1 28',
 '76  9  3 71 77',
 '41 15 61 68 14',
 '',
 '77 86 11 96 50',
 '64 35 76 14  5',
 '31 20 53 84 66',
 '83 40  1 28 79',
 '15 74 92 65 39',
 '',
 '20 55 65 13 48',
 ' 1  3 98 78 29',
 '58 45 39 18 34',
 '43 26 83 33 50',
 '84 15 62 71 88',
 '',
 ' 0 10  3 19 47',
 '51 43 62 11 70',
 '38 59 56 81 55',
 '77 36 39 91 74',
 '23 14 67 12 80',
 '',
 '36 18 47 14 60',
 '33 96 84 44 72',
 ' 1 37 74 93 80',
 '50 95 59 90 27',
 '63 53 65 41 78',
 '',
 '31  4 85 55 74',
 '65 73  2 52  0',
 '99 82 83 25 81',
 '70 75 90 91 89',
 '44 15 53 67 39',
 '',
 '11 39 36 37 32',
 '84 19 58 34 48',
 ' 3 69 81 41 59',
 '86  2 56 47 90',
 '31 12 17 14 40',
 '',
 '28 13 34 45 37',
 '83 55 61 80 92',
 '77 33 44 40 31',
 '54 25 71 56 93',
 '60 70 20 65  9',
 '',
 '82 60 11 40 90',
 ' 0 75 86 55 58',
 '24  9 72 89 56',
 '54 16 22 70 57',
 '64 39 31 33  5',
 '',


In [8]:
boards[:3]

['48 69 68 49 13', '25 14 30 74 89', '16 38 19 24 29']

In [9]:
# Create new boards where every board is empty
board_d = []
i = 0
while(i < len(boards)):
    if(boards[i] == ''):
        board_d.append([])
    i = i + 1
board_d.append([]) # last board


In [10]:
# View empty boards
board_d[:10], len(board_d)

([[], [], [], [], [], [], [], [], [], []], 100)

In [11]:
# Fill empty board
i = 0
for element in boards:
    if element != '':
        board_d[i].append(element)
    else: 
        i = i + 1



In [12]:
# View filled board
board_d[:10]

[['48 69 68 49 13',
  '25 14 30 74 89',
  '16 38 19 24 29',
  '56 97 50 65 79',
  '57 52  5 27 76'],
 ['65 69 73 60 66',
  '79 23 95 32 56',
  '36 51 26  1 28',
  '76  9  3 71 77',
  '41 15 61 68 14'],
 ['77 86 11 96 50',
  '64 35 76 14  5',
  '31 20 53 84 66',
  '83 40  1 28 79',
  '15 74 92 65 39'],
 ['20 55 65 13 48',
  ' 1  3 98 78 29',
  '58 45 39 18 34',
  '43 26 83 33 50',
  '84 15 62 71 88'],
 [' 0 10  3 19 47',
  '51 43 62 11 70',
  '38 59 56 81 55',
  '77 36 39 91 74',
  '23 14 67 12 80'],
 ['36 18 47 14 60',
  '33 96 84 44 72',
  ' 1 37 74 93 80',
  '50 95 59 90 27',
  '63 53 65 41 78'],
 ['31  4 85 55 74',
  '65 73  2 52  0',
  '99 82 83 25 81',
  '70 75 90 91 89',
  '44 15 53 67 39'],
 ['11 39 36 37 32',
  '84 19 58 34 48',
  ' 3 69 81 41 59',
  '86  2 56 47 90',
  '31 12 17 14 40'],
 ['28 13 34 45 37',
  '83 55 61 80 92',
  '77 33 44 40 31',
  '54 25 71 56 93',
  '60 70 20 65  9'],
 ['82 60 11 40 90',
  ' 0 75 86 55 58',
  '24  9 72 89 56',
  '54 16 22 70 57',
  '64 39 31

In [13]:
for board in board_d:
    for i in range(len(board)):
        board[i] = board[i].split(" ")
# View board_d
board_d[:10]

[[['48', '69', '68', '49', '13'],
  ['25', '14', '30', '74', '89'],
  ['16', '38', '19', '24', '29'],
  ['56', '97', '50', '65', '79'],
  ['57', '52', '', '5', '27', '76']],
 [['65', '69', '73', '60', '66'],
  ['79', '23', '95', '32', '56'],
  ['36', '51', '26', '', '1', '28'],
  ['76', '', '9', '', '3', '71', '77'],
  ['41', '15', '61', '68', '14']],
 [['77', '86', '11', '96', '50'],
  ['64', '35', '76', '14', '', '5'],
  ['31', '20', '53', '84', '66'],
  ['83', '40', '', '1', '28', '79'],
  ['15', '74', '92', '65', '39']],
 [['20', '55', '65', '13', '48'],
  ['', '1', '', '3', '98', '78', '29'],
  ['58', '45', '39', '18', '34'],
  ['43', '26', '83', '33', '50'],
  ['84', '15', '62', '71', '88']],
 [['', '0', '10', '', '3', '19', '47'],
  ['51', '43', '62', '11', '70'],
  ['38', '59', '56', '81', '55'],
  ['77', '36', '39', '91', '74'],
  ['23', '14', '67', '12', '80']],
 [['36', '18', '47', '14', '60'],
  ['33', '96', '84', '44', '72'],
  ['', '1', '37', '74', '93', '80'],
  ['50', '

In [14]:
# Each board now has empty strings present
# Remove empty strings
for board in board_d:
    for lis in board:
        while(lis.count('') > 0):
            lis.remove('')
# view board_d

In [15]:
board_d[:5]

[[['48', '69', '68', '49', '13'],
  ['25', '14', '30', '74', '89'],
  ['16', '38', '19', '24', '29'],
  ['56', '97', '50', '65', '79'],
  ['57', '52', '5', '27', '76']],
 [['65', '69', '73', '60', '66'],
  ['79', '23', '95', '32', '56'],
  ['36', '51', '26', '1', '28'],
  ['76', '9', '3', '71', '77'],
  ['41', '15', '61', '68', '14']],
 [['77', '86', '11', '96', '50'],
  ['64', '35', '76', '14', '5'],
  ['31', '20', '53', '84', '66'],
  ['83', '40', '1', '28', '79'],
  ['15', '74', '92', '65', '39']],
 [['20', '55', '65', '13', '48'],
  ['1', '3', '98', '78', '29'],
  ['58', '45', '39', '18', '34'],
  ['43', '26', '83', '33', '50'],
  ['84', '15', '62', '71', '88']],
 [['0', '10', '3', '19', '47'],
  ['51', '43', '62', '11', '70'],
  ['38', '59', '56', '81', '55'],
  ['77', '36', '39', '91', '74'],
  ['23', '14', '67', '12', '80']]]

In [16]:
## Lastly, turn every board element to string
for board in board_d:
    for lis in board:
        for i in range(len(lis)):
            lis[i] = int(lis[i])


In [17]:
# View last 5 board
board_d[:5]

[[[48, 69, 68, 49, 13],
  [25, 14, 30, 74, 89],
  [16, 38, 19, 24, 29],
  [56, 97, 50, 65, 79],
  [57, 52, 5, 27, 76]],
 [[65, 69, 73, 60, 66],
  [79, 23, 95, 32, 56],
  [36, 51, 26, 1, 28],
  [76, 9, 3, 71, 77],
  [41, 15, 61, 68, 14]],
 [[77, 86, 11, 96, 50],
  [64, 35, 76, 14, 5],
  [31, 20, 53, 84, 66],
  [83, 40, 1, 28, 79],
  [15, 74, 92, 65, 39]],
 [[20, 55, 65, 13, 48],
  [1, 3, 98, 78, 29],
  [58, 45, 39, 18, 34],
  [43, 26, 83, 33, 50],
  [84, 15, 62, 71, 88]],
 [[0, 10, 3, 19, 47],
  [51, 43, 62, 11, 70],
  [38, 59, 56, 81, 55],
  [77, 36, 39, 91, 74],
  [23, 14, 67, 12, 80]]]

**Boards and random numbers are now ready**

Convert ran_nums and board_d to numpy arrays

In [18]:
import numpy as np
np_boards = np.array(board_d)
# Check properties of np_board
np_boards.ndim, np_boards.shape, np_boards.dtype

(3, (100, 5, 5), dtype('int32'))

In [19]:
np_rand_nums = np.array(rand_nums)
np_rand_nums.ndim, np_rand_nums.shape, np_rand_nums.dtype

(1, (100,), dtype('int32'))

In [20]:
# Create a binary numpy array to show 
# if number in that position has been checked
# unchecked = 0, checked=1
marked = np.zeros((100, 5, 5), dtype='int')
marked[:5]

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [21]:
# Function to check a board for a bingo
def check_board(marked_board):
    bingo = False;
    # Checking rows
    total = 0
    for row in marked_board:
        for num in row:
            total = total + num
        if(total == len(row)):
            #print(f"{total, len(row)} row")
            bingo = True
            return bingo
        total = 0
    # Checking columns
    # Use this method OR sum every element in a column
    # (if sum == len(marked_board)...Bingo=true)
    total1 = 0
    T = marked_board.T
    for row1 in T:
        for num in row1:
            total1 = total1 + num
        if(total1 == len(row)):
            #print(f"{total, len(row)} row")
            bingo = True
            return bingo 
        total1 = 0
    return bingo
   


In [22]:
# Create a function to check the first board that has a bingo
# and return board number
def check_all_boards(marked_boards):
    #print(marked_boards)
    for i, board in enumerate(marked_boards):
        if(check_board(board)):
            return True, i
    return False, None      

In [23]:
# Function to change marked_board if number is present in board
def mark_board(board, marked_board, num):
    m = marked_board[:]
    #print(num)
    for i, row in enumerate(board):
        for j, val in enumerate(row):
            if num == val:
                m[i][j] = 1
    return m

In [24]:
# Function to mark all boards
def mark_all_boards(boards, marked_boards, num):
    marked = []
    for i, board in enumerate(boards):
        marked.append(mark_board(board, marked_boards[i], num))
    return marked;

In [25]:
# Function to find the winning board and the maked numbers
def play_bingo(boards, nums):
    marked = np.zeros(boards.shape, dtype='int')
    for i, num in enumerate(nums):
        marked = mark_all_boards(boards, marked, num)
        isBingo, bingo_board = check_all_boards(marked)
        if(isBingo):
            return boards[bingo_board], marked[bingo_board], num
    return 'No bingo'

In [26]:
win_board, marker, winning_num = play_bingo(np_boards, rand_nums)
win_board, marker, winning_num

(array([[32, 81, 21, 11, 31],
        [30, 56,  3, 25, 18],
        [80, 96, 20, 65, 71],
        [41, 67, 22, 97, 10],
        [93, 68, 17, 13,  1]]),
 array([[1, 1, 1, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]]),
 21)

**Board 34 was the first board to get bingo**


board_score = sum of unmarked * last_num that won the game

In [27]:
# Calculate sum of unmarked
unmarked_sum = 0
win_board = win_board.tolist()
for i, row in enumerate(win_board):
    for j, num in enumerate(row):
        if(marker[i][j] == 0):
            unmarked_sum = unmarked_sum + win_board[i][j]
unmarked_sum

794

**The above cell can also be turned to a function**

In [28]:
board_score = unmarked_sum * winning_num
board_score

16674

## --- Part Two ---
On the other hand, it might be wise to try a different strategy: let the giant squid win.

You aren't sure how many bingo boards a giant squid could play at once, so rather than waste time counting its arms, the safe thing to do is to figure out which board will win last and choose that one. That way, no matter which boards it picks, it will win for sure.

In the above example, the second board is the last to win, which happens after 13 is eventually called and its middle column is completely marked. If you were to keep playing until this point, the second board would have a sum of unmarked numbers equal to 148 for a final score of 148 * 13 = 1924.

Figure out which board will win last. Once it wins, what would its final score be?

Here we can rewrite the `play_bingo()` function so it returns a list of the winning boards and their markers in the order at which they won

Or you can mutate a variable every win instead of saving every win in an array

In [29]:
def play_bingo2(boards, nums):
    marked = np.zeros(boards.shape, dtype='int')
    boards_s = boards[:].tolist()
    win_boards = []
    win_markers = []
    win_nums = [] # Numbers that triggered their wins
    for i, num in enumerate(nums):
        marked = mark_all_boards(boards_s, marked, num)
        isBingo, bingo_board = check_all_boards(marked)
        while(isBingo):
            win_boards.append(boards_s[bingo_board])
            win_markers.append(marked[bingo_board])
            win_nums.append(num)
            # Remove winners from boards
            boards_s.pop(bingo_board)
            marked.pop(bingo_board)
            isBingo, bingo_board = check_all_boards(marked)
    return win_boards, win_markers, win_nums

In [30]:
win_boards, win_markers, win_nums = play_bingo2(np_boards, rand_nums)
len(win_boards), len(win_markers), len(win_nums)

(100, 100, 100)

In [31]:
last_win_board = win_boards[-1]
last_win_marker = win_markers[-1]
last_win_num = win_nums[-1]

In [32]:
last_win_board

[[1, 27, 74, 89, 4],
 [29, 9, 78, 48, 54],
 [10, 38, 13, 40, 49],
 [71, 73, 79, 77, 17],
 [25, 22, 91, 20, 2]]

In [33]:
last_win_marker

array([[1, 1, 1, 0, 1],
       [1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [34]:
last_win_num

25

In [35]:
# Calculate sum of unmarked
unmarked_sum = 0
for i, row in enumerate(last_win_board):
    for j, num in enumerate(row):
        if(last_win_marker[i][j] == 0):
            unmarked_sum = unmarked_sum + last_win_board[i][j]
unmarked_sum

283

In [36]:
board_score = unmarked_sum * last_win_num
board_score

7075